### ISSUE TITLE
Invalid link to Discord server

### ISSUE THREAD

**Issue by UnrealAlexander** [albertotrunk/UE5-Dream#4]
Currently the https://discord.gg/tmtSqmXf link is coming back as "invalid or has expired" for me. I'm not sure if it's wrong or if the server is private/hidden perhaps. I'd like to join to ask some setup questions. Thanks!

**Comment by albertotrunk** [comment]
Yeah it is expired, here another one!
https://discord.gg/yGf7ygwJ

**Comment by UnrealAlexander** [comment]
Thanks!

**Comment by albertotrunk** [comment]
@UnrealAlexander this repo will be the content examples, the main one for the plugin is in:
https://github.com/albertotrunk/ue-stable-diffusion
